---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy Custom HTML
  copy:
    src: ../templates/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644